baseurl: "/"
languageCode: "en-us"
title: "theyoungobservers.com"
enableEmoji: true
pygmentsCodefences: true
pygmentsStyle: "lovelace"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
canonifyURLs: true
permalinks:
  author: "/author/:slug/"
  
markup:
  goldmark:
    renderer:
      unsafe:
        true

author:
  name: "Andrew Henning"
  email: "HenningBytes@gmail.com"
params:
  title: "Andrew Henning"
  copyright: "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
rssLimit: 50
